//! The cross-provider handoff suite, ported from
//! `packages/ai/test/cross-provider-handoff.test.ts` at commit
//! `60e7e76bd7ea25cad1dd6f3f1ce0d18814a42759`: contexts generated by one
//! provider/model must be consumable by another — tool call id formats,
//! thinking blocks, and message shapes riding the round trip.
//!
//! Like upstream's `it.skipIf`, the suite without any provider credential
//! returns early; fixtures are generated fresh on each run against the live
//! providers the local credential store and env carry.

#![expect(
    clippy::too_many_lines,
    reason = "the fixture and handoff drivers mirror upstream's flat structure"
)]
#![expect(
    clippy::print_stdout,
    reason = "the suite logs fixture and handoff progress like upstream's console.log"
)]
#![expect(
    deprecated,
    reason = "the suite drives the deprecated compat surface, upstream's cast getModel"
)]
#![expect(
    clippy::significant_drop_tightening,
    reason = "the registry guard is held for each test's whole run on purpose; the suites must not interleave"
)]

use std::collections::{BTreeMap, BTreeSet};
use std::sync::{Arc, Mutex, OnceLock};

use pi_ai::auth::resolve::now_ms;
use pi_ai::compat::{complete_simple, get_env_api_key, get_model};
use pi_ai::types::{
    Api, AssistantBlock, Context, Message, Model, ProviderHeaders, SimpleStreamOptions, StopReason,
    ThinkingLevel, ToolResultBlock, ToolResultMessage, UserContent, UserMessage,
};

mod common;

/// The tool the fixtures exercise, upstream's `testTool` over
/// `Type.Object({ value: Type.Number() })` — typebox requires every property.
fn test_tool() -> pi_ai::types::Tool {
    pi_ai::types::Tool {
        name: "double_number".to_owned(),
        description: "Doubles a number and returns the result".to_owned(),
        parameters: serde_json::json!({
            "type": "object",
            "properties": {
                "value": { "type": "number", "description": "A number to double" }
            },
            "required": ["value"]
        }),
        constrained_sampling: None,
    }
}

/// One provider/model pair the suite generates a fixture for and handoffs
/// into, upstream's `ProviderModelPair`.
#[derive(Clone, Copy)]
struct ProviderModelPair {
    provider: &'static str,
    model: &'static str,
    label: &'static str,
    api_override: Option<&'static str>,
    upstream_api_key_env: Option<&'static str>,
}

const fn pair(
    provider: &'static str,
    model: &'static str,
    label: &'static str,
) -> ProviderModelPair {
    ProviderModelPair {
        provider,
        model,
        label,
        api_override: None,
        upstream_api_key_env: None,
    }
}

/// The provider/model pairs the suite covers, upstream's
/// `PROVIDER_MODEL_PAIRS` at the pinned catalog.
const PROVIDER_MODEL_PAIRS: [ProviderModelPair; 42] = [
    // Anthropic
    pair(
        "anthropic",
        "claude-sonnet-4-5",
        "anthropic-claude-sonnet-4-5",
    ),
    // Google
    pair(
        "google",
        "gemini-3-flash-preview",
        "google-gemini-3-flash-preview",
    ),
    // OpenAI
    ProviderModelPair {
        api_override: Some("openai-completions"),
        ..pair("openai", "gpt-4o-mini", "openai-completions-gpt-4o-mini")
    },
    pair("openai", "gpt-5-mini", "openai-responses-gpt-5-mini"),
    pair(
        "azure-openai-responses",
        "gpt-4o-mini",
        "azure-openai-responses-gpt-4o-mini",
    ),
    // OpenAI Codex
    pair("openai-codex", "gpt-5.5", "openai-codex-gpt-5.5"),
    // GitHub Copilot
    pair(
        "github-copilot",
        "claude-sonnet-4.5",
        "copilot-claude-sonnet-4.5",
    ),
    pair("github-copilot", "gpt-5.1-codex", "copilot-gpt-5.1-codex"),
    pair(
        "github-copilot",
        "gemini-3-flash-preview",
        "copilot-gemini-3-flash-preview",
    ),
    pair(
        "github-copilot",
        "grok-code-fast-1",
        "copilot-grok-code-fast-1",
    ),
    // Amazon Bedrock
    pair(
        "amazon-bedrock",
        "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        "bedrock-claude-sonnet-4-5",
    ),
    // xAI
    pair("xai", "grok-4.3", "xai-grok-4.3"),
    // Cerebras
    pair("cerebras", "zai-glm-4.7", "cerebras-zai-glm-4.7"),
    // Cloudflare Workers AI
    pair(
        "cloudflare-workers-ai",
        "@cf/moonshotai/kimi-k2.6",
        "cloudflare-kimi-k2.6",
    ),
    // Cloudflare AI Gateway
    pair(
        "cloudflare-ai-gateway",
        "workers-ai/@cf/moonshotai/kimi-k2.6",
        "cloudflare-gateway-kimi-k2.6",
    ),
    ProviderModelPair {
        upstream_api_key_env: Some("ANTHROPIC_API_KEY"),
        ..pair(
            "cloudflare-ai-gateway",
            "claude-sonnet-4-5",
            "cloudflare-gateway-claude-sonnet-4-5",
        )
    },
    ProviderModelPair {
        upstream_api_key_env: Some("OPENAI_API_KEY"),
        ..pair(
            "cloudflare-ai-gateway",
            "gpt-5.1",
            "cloudflare-gateway-gpt-5.1",
        )
    },
    // Groq
    pair("groq", "openai/gpt-oss-120b", "groq-gpt-oss-120b"),
    // Hugging Face
    pair(
        "huggingface",
        "moonshotai/Kimi-K2.5",
        "huggingface-kimi-k2.5",
    ),
    // Together AI
    pair("together", "moonshotai/Kimi-K2.6", "together-kimi-k2.6"),
    // Baseten
    pair("baseten", "zai-org/GLM-5.2", "baseten-glm-5.2"),
    // Kimi For Coding
    pair("kimi-coding", "kimi-for-coding", "kimi-for-coding"),
    // Mistral
    pair(
        "mistral",
        "devstral-medium-latest",
        "mistral-devstral-medium",
    ),
    // MiniMax
    pair("minimax", "MiniMax-M2.7", "minimax-m2.7"),
    pair("minimax-cn", "MiniMax-M2.7", "minimax-m2.7"),
    // OpenCode Zen
    pair("opencode", "big-pickle", "zen-big-pickle"),
    pair("opencode", "claude-sonnet-4-5", "zen-claude-sonnet-4-5"),
    pair("opencode", "gemini-3-flash", "zen-gemini-3-flash"),
    pair("opencode", "glm-4.7-free", "zen-glm-4.7-free"),
    pair("opencode", "gpt-5.2-codex", "zen-gpt-5.2-codex"),
    pair("opencode", "minimax-m2.1-free", "zen-minimax-m2.1-free"),
    // OpenCode Go
    pair("opencode-go", "kimi-k2.5", "go-kimi-k2.5"),
    pair("opencode-go", "minimax-m2.5", "go-minimax-m2.5"),
    // Xiaomi MiMo
    pair("xiaomi", "mimo-v2.5-pro", "xiaomi-mimo-v2.5-pro"),
    pair(
        "xiaomi-token-plan-cn",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-cn-mimo-v2.5-pro",
    ),
    pair(
        "xiaomi-token-plan-ams",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-ams-mimo-v2.5-pro",
    ),
    pair(
        "xiaomi-token-plan-sgp",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-sgp-mimo-v2.5-pro",
    ),
    // Qwen Token Plan
    pair(
        "qwen-token-plan",
        "qwen3.7-max",
        "qwen-token-plan-qwen3.7-max",
    ),
    pair(
        "qwen-token-plan-cn",
        "qwen3.7-max",
        "qwen-token-plan-cn-qwen3.7-max",
    ),
    pair(
        "qwen-token-plan-individual",
        "qwen3.8-max",
        "qwen-token-plan-individual-qwen3.8-max",
    ),
    pair(
        "qwen-token-plan-individual",
        "deepseek-v4-flash-0731",
        "qwen-token-plan-individual-deepseek-v4-flash-0731",
    ),
    pair(
        "qwen-token-plan-individual",
        "glm-5.2",
        "qwen-token-plan-individual-glm-5.2",
    ),
];

/// One generated fixture context, upstream's `CachedContext`.
#[expect(
    dead_code,
    reason = "the cached fixture metadata mirrors upstream's shape; assertions read only what they use"
)]
struct CachedContext {
    label: String,
    provider: String,
    model: String,
    api: Api,
    messages: Vec<Message>,
    /// Wall-clock stamp of the generation, upstream's ISO `generatedAt`; the
    /// value never leaves the process.
    generated_at: i64,
}

/// The sync credential check the suite gates with, upstream's `hasApiKey`:
/// env vars only, with the azure and cloudflare deployments' multi-var gates.
fn has_api_key(pair: &ProviderModelPair) -> bool {
    if pair.provider == "azure-openai-responses" {
        return common::live::has_azure_openai_credentials();
    }
    if pair.provider == "cloudflare-workers-ai" {
        return common::live::has_cloudflare_workers_ai_credentials();
    }
    if pair.provider == "cloudflare-ai-gateway" {
        if !common::live::has_cloudflare_ai_gateway_credentials() {
            return false;
        }
        return pair
            .upstream_api_key_env
            .is_none_or(|env_var| std::env::var(env_var).is_ok_and(|value| !value.is_empty()));
    }
    get_env_api_key(pair.provider, None).is_some()
}

/// Whether any provider has credentials available, upstream's
/// `hasAnyApiKey`.
fn has_any_api_key() -> bool {
    PROVIDER_MODEL_PAIRS.iter().any(has_api_key)
}

/// The upstream-auth headers a gateway probe rides, upstream's `getHeaders`.
fn get_headers(pair: &ProviderModelPair) -> Option<ProviderHeaders> {
    let upstream_env = pair.upstream_api_key_env?;
    let upstream_api_key = std::env::var(upstream_env).ok()?;
    Some(BTreeMap::from([(
        "Authorization".to_owned(),
        Some(format!("Bearer {upstream_api_key}")),
    )]))
}

/// The failure dump, upstream's `dumpFailurePayload`: label, error, payload,
/// and messages into a temp JSON file for post-mortem.
fn dump_failure_payload(
    label: &str,
    error: &str,
    payload: Option<&serde_json::Value>,
    messages: &[Message],
) {
    let filename = std::env::temp_dir().join(format!("pi-handoff-{label}-{}.json", now_ms()));
    let body = serde_json::json!({
        "label": label,
        "error": error,
        "payload": payload,
        "messages": messages,
    });
    if let Ok(serialized) = serde_json::to_string_pretty(&body) {
        std::fs::write(&filename, serialized).ok();
        println!("Wrote failure payload to {}", filename.display());
    }
}

/// The last-payload slot a probe's request hook fills.
type LastPayload = Arc<Mutex<Option<serde_json::Value>>>;

/// The request-payload hook recording the outgoing payload, upstream's
/// `onPayload: (payload) => { lastPayload = payload }`.
fn payload_hook(slot: LastPayload) -> pi_ai::types::OnPayload {
    pi_ai::types::OnPayload::new(move |payload, _model| {
        *slot
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner) = Some(payload);
        Box::pin(async { None })
    })
}

/// The simple-request options a probe carries, upstream's inline
/// `{ apiKey, reasoning, headers, onPayload }`.
fn probe_options(
    api_key: &str,
    reasoning: Option<ThinkingLevel>,
    headers: Option<ProviderHeaders>,
    last_payload: LastPayload,
) -> SimpleStreamOptions {
    SimpleStreamOptions {
        api_key: Some(api_key.to_owned()),
        reasoning,
        headers,
        transport_options: pi_ai::types::TransportOptions {
            on_payload: Some(payload_hook(last_payload)),
            ..pi_ai::types::TransportOptions::default()
        },
        ..SimpleStreamOptions::default()
    }
}

/// The model a pair drives, upstream's api-override spread over the catalog
/// read.
fn pair_model(pair: &ProviderModelPair) -> Option<Model> {
    let mut model = get_model(pair.provider, pair.model)?;
    if let Some(api_override) = pair.api_override {
        model.api = Api::from(api_override);
    }
    Some(model)
}

/// One fixture context from a provider/model pair, upstream's
/// `generateContext`: the tool-call round trip and the final response, or
/// `None` when the provider could not serve one. Upstream's caught rejections
/// fold into the error-terminal message the stream settles with.
async fn generate_context(pair: &ProviderModelPair, api_key: &str) -> Option<(Vec<Message>, Api)> {
    let Some(model) = pair_model(pair) else {
        println!("  Model not found: {}/{}", pair.provider, pair.model);
        return None;
    };

    let user_message = Message::User(UserMessage {
        content: UserContent::Text(
            "Please double the number 21 using the double_number tool.".to_owned(),
        ),
        timestamp: now_ms(),
    });
    let supports_reasoning = model.reasoning;
    let headers = get_headers(pair);
    let last_payload: LastPayload = Arc::new(Mutex::new(None));
    let options = probe_options(
        api_key,
        supports_reasoning.then_some(ThinkingLevel::High),
        headers.clone(),
        Arc::clone(&last_payload),
    );

    let initial_context = Context {
        system_prompt: Some(
            "You are a helpful assistant. Use the provided tool to complete the task.".to_owned(),
        ),
        messages: vec![user_message.clone()],
        tools: Some(vec![test_tool()]),
    };

    let assistant_response = complete_simple(&model, &initial_context, Some(&options)).await;
    if assistant_response.stop_reason == StopReason::Error {
        println!(
            "  Initial request error: {}",
            assistant_response
                .error_message
                .as_deref()
                .unwrap_or("Unknown error")
        );
        dump_failure_payload(
            &format!("{}-initial", pair.label),
            assistant_response
                .error_message
                .as_deref()
                .unwrap_or("Unknown error"),
            last_payload
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner)
                .as_ref(),
            initial_context.messages.as_slice(),
        );
        return None;
    }

    let Some(tool_call) = assistant_response
        .content
        .iter()
        .find_map(|block| match block {
            AssistantBlock::ToolCall(call) => Some(call),
            _ => None,
        })
    else {
        println!(
            "  No tool call in response (stopReason: {:?})",
            assistant_response.stop_reason
        );
        return Some((
            vec![user_message, Message::Assistant(assistant_response)],
            model.api.clone(),
        ));
    };

    println!("  Tool call ID: {}", tool_call.id);

    let tool_result = Message::ToolResult(ToolResultMessage {
        tool_call_id: tool_call.id.clone(),
        tool_name: tool_call.name.clone(),
        content: vec![ToolResultBlock::Text(common::text_block("42"))],
        details: None,
        usage: None,
        added_tool_names: None,
        is_error: false,
        timestamp: now_ms(),
    });

    let messages_for_final = vec![
        user_message,
        Message::Assistant(assistant_response),
        tool_result,
    ];
    let final_context = Context {
        system_prompt: Some("You are a helpful assistant.".to_owned()),
        messages: messages_for_final.clone(),
        tools: Some(vec![test_tool()]),
    };
    let options = probe_options(
        api_key,
        supports_reasoning.then_some(ThinkingLevel::High),
        headers.clone(),
        Arc::clone(&last_payload),
    );

    let final_response = complete_simple(&model, &final_context, Some(&options)).await;
    if final_response.stop_reason == StopReason::Error {
        println!(
            "  Final request error: {}",
            final_response
                .error_message
                .as_deref()
                .unwrap_or("Unknown error")
        );
        dump_failure_payload(
            &format!("{}-final", pair.label),
            final_response
                .error_message
                .as_deref()
                .unwrap_or("Unknown error"),
            last_payload
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner)
                .as_ref(),
            messages_for_final.as_slice(),
        );
        return None;
    }

    Some((
        vec![
            messages_for_final[0].clone(),
            messages_for_final[1].clone(),
            messages_for_final[2].clone(),
            Message::Assistant(final_response),
        ],
        model.api.clone(),
    ))
}

/// The fixture state the two suite tests share, upstream's `beforeAll`
/// bindings held in the describe scope.
struct FixtureState {
    contexts: BTreeMap<String, CachedContext>,
    available: Vec<ProviderModelPair>,
    built: bool,
}

/// The shared fixture state, built once per process, upstream's
/// `beforeAll` build over the credential-carrying pairs.
async fn fixtures() -> tokio::sync::MutexGuard<'static, FixtureState> {
    static FIXTURES: OnceLock<tokio::sync::Mutex<FixtureState>> = OnceLock::new();
    let mutex = FIXTURES.get_or_init(|| {
        tokio::sync::Mutex::new(FixtureState {
            contexts: BTreeMap::new(),
            available: Vec::new(),
            built: false,
        })
    });
    let mut state = mutex.lock().await;
    if !state.built {
        println!("\n=== Generating Fixtures ===\n");
        for candidate in &PROVIDER_MODEL_PAIRS {
            let Some(api_key) = common::live::resolve_api_key(candidate.provider).await else {
                println!(
                    "[{}] Skipping - no auth for {}",
                    candidate.label, candidate.provider
                );
                continue;
            };
            if !has_api_key(candidate) {
                println!(
                    "[{}] Skipping - no auth for {}",
                    candidate.label, candidate.provider
                );
                continue;
            }

            println!("[{}] Generating fixture...", candidate.label);
            let Some((messages, api)) = generate_context(candidate, &api_key).await else {
                println!("[{}] Failed to generate fixture, skipping", candidate.label);
                continue;
            };
            if messages.len() < 4 {
                println!("[{}] Failed to generate fixture, skipping", candidate.label);
                continue;
            }

            println!(
                "[{}] Generated {} messages",
                candidate.label,
                messages.len()
            );
            state.contexts.insert(
                candidate.label.to_owned(),
                CachedContext {
                    label: candidate.label.to_owned(),
                    provider: candidate.provider.to_owned(),
                    model: candidate.model.to_owned(),
                    api: api.clone(),
                    messages,
                    generated_at: now_ms(),
                },
            );
            state.available.push(*candidate);
        }
        println!(
            "\n=== {}/{} contexts available ===\n",
            state.available.len(),
            PROVIDER_MODEL_PAIRS.len()
        );
        state.built = true;
    }
    state
}

/// The suite's fixture count gate, upstream's `should have at least 2
/// fixtures to test handoffs`.
#[tokio::test]
async fn should_have_at_least_2_fixtures_to_test_handoffs() {
    let _guard = common::registry_guard().await;
    if !has_any_api_key() {
        println!("skipping — no provider credentials");
        return;
    }
    let state = fixtures().await;
    assert!(
        state.contexts.len() >= 2,
        "expected at least 2 fixture contexts, got {}",
        state.contexts.len()
    );
}

/// Every available target consumes the other contexts' messages and answers,
/// upstream's `should handle cross-provider handoffs for each target`.
#[tokio::test]
async fn should_handle_cross_provider_handoffs_for_each_target() {
    let _guard = common::registry_guard().await;
    if !has_any_api_key() {
        println!("skipping — no provider credentials");
        return;
    }
    let state = fixtures().await;

    if state.contexts.len() < 2 {
        println!("Not enough fixtures for handoff test, skipping");
        return;
    }

    println!("\n=== Testing Cross-Provider Handoffs ===\n");

    let mut results: Vec<(String, bool, Option<String>)> = Vec::new();
    for target_pair in &state.available {
        let Some(api_key) = common::live::resolve_api_key(target_pair.provider).await else {
            println!("[Target: {}] Skipping - no auth", target_pair.label);
            continue;
        };
        if !has_api_key(target_pair) {
            println!("[Target: {}] Skipping - no auth", target_pair.label);
            continue;
        }

        let mut other_messages: Vec<Message> = Vec::new();
        for (label, context) in &state.contexts {
            if label == target_pair.label {
                continue;
            }
            other_messages.extend(context.messages.iter().cloned());
        }

        if other_messages.is_empty() {
            println!(
                "[Target: {}] Skipping - no other contexts",
                target_pair.label
            );
            continue;
        }

        other_messages.push(Message::User(UserMessage {
            content: UserContent::Text(
                "Great, thanks for all that help! Now just say 'Hello, handoff successful!' to confirm you received everything.".to_owned(),
            ),
            timestamp: now_ms(),
        }));

        let Some(model) = pair_model(target_pair) else {
            println!("[Target: {}] Model not found", target_pair.label);
            continue;
        };
        let supports_reasoning = model.reasoning;
        let headers = get_headers(target_pair);

        println!(
            "[Target: {}] Testing with {} messages from other providers...",
            target_pair.label,
            other_messages.len()
        );

        let last_payload: LastPayload = Arc::new(Mutex::new(None));
        let options = probe_options(
            &api_key,
            supports_reasoning.then_some(ThinkingLevel::High),
            headers.clone(),
            Arc::clone(&last_payload),
        );
        let handoff_context = Context {
            system_prompt: Some("You are a helpful assistant.".to_owned()),
            messages: other_messages.clone(),
            tools: Some(vec![test_tool()]),
        };

        let response = complete_simple(&model, &handoff_context, Some(&options)).await;

        if response.stop_reason == StopReason::Error {
            println!(
                "[Target: {}] FAILED: {}",
                target_pair.label,
                response.error_message.as_deref().unwrap_or("Unknown error")
            );
            dump_failure_payload(
                target_pair.label,
                response.error_message.as_deref().unwrap_or("Unknown error"),
                last_payload
                    .lock()
                    .unwrap_or_else(std::sync::PoisonError::into_inner)
                    .as_ref(),
                handoff_context.messages.as_slice(),
            );
            results.push((
                target_pair.label.to_owned(),
                false,
                response.error_message.clone(),
            ));
        } else {
            let text = response
                .content
                .iter()
                .filter_map(|block| match block {
                    AssistantBlock::Text(text) => Some(text.text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join(" ");
            let preview = text
                .chars()
                .take(100)
                .collect::<String>()
                .replace('\n', " ");
            println!("[Target: {}] SUCCESS: {preview}...", target_pair.label);
            results.push((target_pair.label.to_owned(), true, None));
        }
    }

    println!("\n=== Results Summary ===\n");
    let successes = results.iter().filter(|(_, success, _)| *success).count();
    let failures: Vec<&(String, bool, Option<String>)> =
        results.iter().filter(|(_, success, _)| !success).collect();
    println!("Passed: {successes}/{}", results.len());
    if !failures.is_empty() {
        println!("\nFailures:");
        for (target, _, error) in &failures {
            println!("  - {target}: {}", error.as_deref().unwrap_or(""));
        }
    }
    assert!(
        failures.is_empty(),
        "the handoff round trips carried failures: {:?}",
        failures
            .iter()
            .map(|(target, _, _)| target)
            .collect::<BTreeSet<_>>()
    );
}
